from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

# Static-site "build": no bundler, no backend -- per issue #33's constraints
# (no over-engineering). system/runtime/data/kabukicho/ is the canonical data
# source; this copies it plus the static HTML/JS/CSS into two places:
#   - this product dir's own data/ (so index.html can be opened/served locally)
#   - web/public/kabukicho/ (the deployable static bundle)

PRODUCT_DIR = Path(__file__).resolve().parent
REPO_ROOT = PRODUCT_DIR.parents[2]
DATA_SOURCE = REPO_ROOT / "system" / "runtime" / "data" / "kabukicho"
PUBLIC_DIR = REPO_ROOT / "web" / "public" / "kabukicho"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from system.core.dotenv import load_dotenv  # noqa: E402

STATIC_FILES = ("index.html", "app.js", "style.css")
LOCAL_CONFIG_FILE = PRODUCT_DIR / "local.config.js"


def build() -> None:
    if not DATA_SOURCE.exists():
        raise FileNotFoundError(f"Data source not found: {DATA_SOURCE}")

    local_data_dir = PRODUCT_DIR / "data"
    public_data_dir = PUBLIC_DIR / "data"
    local_data_dir.mkdir(parents=True, exist_ok=True)
    public_data_dir.mkdir(parents=True, exist_ok=True)

    for data_file in DATA_SOURCE.glob("*.json"):
        shutil.copy2(data_file, local_data_dir / data_file.name)
        shutil.copy2(data_file, public_data_dir / data_file.name)

    for static_file in STATIC_FILES:
        shutil.copy2(PRODUCT_DIR / static_file, PUBLIC_DIR / static_file)

    print(f"Copied {len(list(DATA_SOURCE.glob('*.json')))} data file(s) to {local_data_dir} and {public_data_dir}")
    print(f"Copied {len(STATIC_FILES)} static file(s) to {PUBLIC_DIR}")

    _write_local_gmaps_config()


def _write_local_gmaps_config() -> None:
    # Local-dev-only convenience: if the operator has set a real Google
    # Maps JS API key in .env, write it into a small, gitignored file that
    # index.html loads (as a script tag, before the window.KABUKICHO_
    # GMAPS_API_KEY placeholder) purely so the map renders during local
    # testing. Deliberately NOT written into PUBLIC_DIR -- that bundle is
    # tracked in git, and this key must never be committed there. A real
    # production deploy needs its own separate key-injection step, tied to
    # whichever host is eventually chosen (not yet decided).
    # load_dotenv() populates os.environ as a side effect (without
    # overriding a variable already set in the real shell environment) --
    # read back from there, matching this repo's established convention
    # (see system/scripts/somia/providers_kling.py) rather than relying on
    # its returned dict, which only reflects the file, not a real
    # shell-exported KABUKICHO_GMAPS_API_KEY.
    load_dotenv(REPO_ROOT / ".env")
    api_key = os.environ.get("KABUKICHO_GMAPS_API_KEY", "")
    if not api_key:
        if LOCAL_CONFIG_FILE.exists():
            LOCAL_CONFIG_FILE.unlink()
        return
    LOCAL_CONFIG_FILE.write_text(
        "// Generated by build.py from .env's KABUKICHO_GMAPS_API_KEY.\n"
        "// Local dev only -- gitignored, never committed, never copied to\n"
        "// web/public/kabukicho/. Do not edit by hand; edit .env instead.\n"
        f"window.KABUKICHO_GMAPS_API_KEY = {json.dumps(api_key)};\n",
        encoding="utf-8",
    )
    print(f"Wrote local Google Maps API key to {LOCAL_CONFIG_FILE} (local dev only, not committed)")


if __name__ == "__main__":
    build()
