// Generated by build.py from .env's KABUKICHO_GMAPS_API_KEY.
// Local dev only -- gitignored, never committed, never copied to
// platform/web/public/kabukicho/. Do not edit by hand; edit .env instead.
window.KABUKICHO_GMAPS_API_KEY = "AIzaSyCZqdbSfzM8Wzu4-J2Vd5pfm5iN0yCaA2w";
